services:
  sqlserver:
    #    image: mcr.microsoft.com/mssql/server:2019-latest
    image: rapidfort/microsoft-sql-server-2019-ib
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "Str0ngP@ssw0rd!"
    ports:
      - "1433:1433"
#    volumes:
#      - sqlserver_data:/var/opt/mssql/data
#volumes:
#  sqlserver_data: